import React, { useMemo, useState } from 'react';
import { useData } from '../../context/DataContext.tsx';
import { UniversalActivity } from '../../models/types.ts';
import { Activity, Clock, Navigation, Search, Filter } from 'lucide-react';
import { useNavigate } from 'react-router-dom';

interface ClusterNode {
    id: string; // The normalized name
    name: string; // Display name
    type: 'running' | 'strength' | 'cycling' | 'other';
    activities: UniversalActivity[];
    count: number;
    avgDistance?: number;
    avgDuration?: number;
}

export function WorkoutLibraryTab() {
    const { universalActivities } = useData();
    const navigate = useNavigate();
    const [search, setSearch] = useState("");
    const [typeFilter, setTypeFilter] = useState<'all' | 'running' | 'strength' | 'cycling'>('all');

    const clusters = useMemo(() => {
        const groups = new Map<string, ClusterNode>();

        // We want to ignore generic autogenerated names if possible, or maybe just group everything so the user sees it.
        const ignoredNames = ['morgonlöpning', 'lunchlöpning', 'kvällslöpning', 'eftermiddagslöpning', 'strava activity', '-'];

        universalActivities.forEach(act => {
            if (!act.performance && !act.plan) return;

            // Extract the best title
            let rawTitle = act.plan?.title || act.performance?.notes || act.performance?.source?.name || '-';
            
            // Normalize
            let normalized = rawTitle.toLowerCase().trim();

            // Ignore totally generic strava names
            if (ignoredNames.includes(normalized)) {
                normalized = 'distans (ospecificerad)'; // fallback cluster for generic runs
            }

            // Determine type
            const type = act.performance?.activityType === 'strength' || act.type === 'strength' ? 'strength' 
                : act.performance?.activityType === 'cycling' || act.type === 'cycling' ? 'cycling'
                : act.performance?.activityType === 'running' || act.type === 'running' ? 'running' 
                : 'other';

            if (typeFilter !== 'all' && type !== typeFilter) return;

            const clusterId = `${type}-${normalized}`;

            if (!groups.has(clusterId)) {
                groups.set(clusterId, {
                    id: clusterId,
                    name: rawTitle === '-' || ignoredNames.includes(rawTitle.toLowerCase().trim()) ? 'Distans (Ospecificerad)' : rawTitle,
                    type,
                    activities: [],
                    count: 0
                });
            }

            const node = groups.get(clusterId)!;
            node.activities.push(act);
            node.count += 1;
        });

        // Calculate averages
        const result = Array.from(groups.values()).map(node => {
            if (node.type === 'running' || node.type === 'cycling') {
                let totalDist = 0;
                let totalDur = 0;
                let validDist = 0;
                let validDur = 0;
                node.activities.forEach(a => {
                    if (a.performance?.metrics?.distance) { totalDist += a.performance.metrics.distance; validDist++; }
                    if (a.performance?.metrics?.duration) { totalDur += a.performance.metrics.duration; validDur++; }
                });
                if (validDist > 0) node.avgDistance = totalDist / validDist;
                if (validDur > 0) node.avgDuration = totalDur / validDur;
            }
            return node;
        });

        // Sort by count descending
        return result.sort((a, b) => b.count - a.count);
    }, [universalActivities, typeFilter]);

    const filteredClusters = useMemo(() => {
        return clusters.filter(c => c.name.toLowerCase().includes(search.toLowerCase()));
    }, [clusters, search]);

    return (
        <div className="space-y-6 animate-in fade-in">
            {/* Top Bar */}
            <div className="flex flex-col md:flex-row gap-4 items-center bg-slate-900/50 p-4 rounded-2xl border border-white/5">
                <div className="relative flex-1 w-full">
                    <Search className="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-slate-500" />
                    <input 
                        type="text" 
                        value={search}
                        onChange={e => setSearch(e.target.value)}
                        placeholder="Sök på passnamn (t.ex. 400m, tröskel)..."
                        className="w-full bg-slate-950 border border-slate-800 rounded-xl py-3 pl-12 pr-4 text-white focus:border-indigo-500 outline-none transition-colors"
                    />
                </div>
                <div className="flex gap-2 w-full md:w-auto">
                    {(['all', 'running', 'strength', 'cycling'] as const).map(t => (
                        <button
                            key={t}
                            onClick={() => setTypeFilter(t)}
                            className={`px-4 py-3 rounded-xl text-xs font-bold uppercase tracking-widest transition-all flex-1 md:flex-none text-center ${typeFilter === t ? 'bg-indigo-600 text-white' : 'bg-slate-800 text-slate-400 hover:text-white'}`}
                        >
                            {t === 'all' ? 'Alla' : t === 'running' ? 'Löpning' : t === 'strength' ? 'Styrka' : 'Cykel'}
                        </button>
                    ))}
                </div>
            </div>

            {/* Clusters Grid */}
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                {filteredClusters.map(cluster => (
                    <div 
                        key={cluster.id} 
                        onClick={() => navigate('/workouts/builder', { state: { title: cluster.name, category: cluster.type.toUpperCase() } })}
                        className="bg-slate-900 border border-white/5 p-6 rounded-[2rem] hover:border-indigo-500/50 hover:bg-indigo-900/10 transition-all group flex flex-col cursor-pointer shadow-xl hover:shadow-indigo-500/10"
                    >
                        <div className="flex items-start justify-between mb-4">
                            <div className="w-12 h-12 rounded-2xl bg-slate-950 flex items-center justify-center border border-white/5 text-xl">
                                {cluster.type === 'running' ? '🏃' : cluster.type === 'strength' ? '🏋️' : cluster.type === 'cycling' ? '🚴' : '📝'}
                            </div>
                            <div className="bg-indigo-500/10 border border-indigo-500/20 text-indigo-400 px-3 py-1 rounded-lg text-xs font-black uppercase tracking-widest">
                                {cluster.count} pass
                            </div>
                        </div>

                        <h3 className="text-xl font-black text-white mb-2 leading-tight group-hover:text-indigo-400 transition-colors">
                            {cluster.name}
                        </h3>

                        <div className="mt-auto pt-4 border-t border-white/5 flex gap-4">
                            {cluster.avgDistance !== undefined && (
                                <div className="flex items-center gap-1.5 text-slate-400">
                                    <Navigation className="w-4 h-4" />
                                    <span className="text-sm font-bold">{cluster.avgDistance.toFixed(1)} km</span>
                                </div>
                            )}
                            {cluster.avgDuration !== undefined && (
                                <div className="flex items-center gap-1.5 text-slate-400">
                                    <Clock className="w-4 h-4" />
                                    <span className="text-sm font-bold">{Math.round(cluster.avgDuration)} min</span>
                                </div>
                            )}
                        </div>
                    </div>
                ))}
            </div>

            {filteredClusters.length === 0 && (
                <div className="text-center py-20 text-slate-500">
                    Hittade inga aktiviteter som matchar sökningen.
                </div>
            )}
        </div>
    );
}
