import { Pipeline, GuardianContext } from "./middleware/core.ts";
import { LoggerMiddleware, RecorderMiddleware } from "./middleware/logging.ts";
import { BlockListMiddleware, BotDefenseMiddleware, WafMiddleware, TokenBucketRateLimitMiddleware } from "./middleware/security.ts";
import { SmartCacheMiddleware } from "./middleware/cache.ts";
import { CircuitBreakerMiddleware } from "./middleware/resilience.ts";
import { ProxyMiddleware } from "./middleware/proxy.ts";
import { manager } from "./services.ts";

// Build Pipeline
const pipeline = new Pipeline()
    .use(new LoggerMiddleware())
    .use(new BlockListMiddleware())
    .use(new TokenBucketRateLimitMiddleware())
    .use(new BotDefenseMiddleware())
    .use(new WafMiddleware())
    .use(new SmartCacheMiddleware())
    .use(new RecorderMiddleware())
    .use(new CircuitBreakerMiddleware())
    .use(new ProxyMiddleware());

const MAINTENANCE_HTML = `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Maintenance - Guardian</title>
    <style>
        body { background: #0f172a; color: #f8fafc; font-family: system-ui; display: flex; align-items: center; justify-content: center; height: 100vh; margin: 0; }
        .container { text-align: center; }
        h1 { color: #3b82f6; }
    </style>
</head>
<body>
    <div class="container">
        <h1>System Maintenance</h1>
        <p>This service is currently stopped or restarting.</p>
        <p>Please try again in a moment.</p>
    </div>
</body>
</html>
`;

export async function handleProxyRequest(
    req: Request,
    info: Deno.ServeHandlerInfo,
    targetPort: number,
    serviceName: string
): Promise<Response> {
    // 1. Check Service Status (Global Switch)
    const service = manager.get(serviceName);
    if (service && service.stats.status === "stopped") {
         return new Response(MAINTENANCE_HTML, {
             status: 503,
             headers: { "content-type": "text/html" }
         });
    }

    // 2. Build Context
    const url = new URL(req.url);
    const ip = (info.remoteAddr as Deno.NetAddr).hostname;
    const userAgent = req.headers.get("user-agent") || "unknown";

    const ctx: GuardianContext = {
        req,
        info,
        url,
        ip,
        userAgent,
        serviceName,
        targetPort,
        sessionId: "", // Will be generated by LoggerMiddleware
        requestId: crypto.randomUUID(),
        startTime: performance.now()
    };

    // 3. Execute Pipeline
    try {
        return await pipeline.execute(ctx);
    } catch (e) {
        console.error(`[GUARDIAN] Critical Pipeline Error: ${e}`);
        return new Response("Guardian Internal Error", { status: 500 });
    }
}
